task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 80 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /Users/yuansu/Desktop/codes/dataset/coco128/images/train2017
    ann_file: /Users/yuansu/Desktop/codes/dataset/coco128/cocolabels/train_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 2
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /Users/yuansu/Desktop/codes/dataset/coco128/images/train2017
    ann_file: /Users/yuansu/Desktop/codes/dataset/coco128/cocolabels/train_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 2
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

